# Pick a softer palette.
set -g @catppuccin_flavor 'latte'
# Mouse 
set -g mouse on
# hyperlink
set -as terminal-features ",*:hyperlinks"
# Start window indices at 1
set -g base-index 1
# Start pane indices at 1
setw -g pane-base-index 1
# launch
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
